import React, {createContext, useContext, useState} from 'react';
import {calculate, defaults, bounds} from './calculator.mjs';
import {materials, defaultMaterial} from './materials.mjs';
const Context=createContext(null);
const useCalculator=()=>useContext(Context);
const money=new Intl.NumberFormat('ru-BY',{minimumFractionDigits:2,maximumFractionDigits:2});
const num=(v,d=1)=>new Intl.NumberFormat('ru-BY',{maximumFractionDigits:d}).format(v);
const dimensions=['x','y','z'];
const initialValues=()=>Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,v===null?'':String(v)]));
const labels={material:'Пластик',energy:'Электричество',wear:'Износ принтера',maintenance:'Обслуживание',labor:'Ручная работа',consumables:'Расходники',extra:'Другие расходы'};
const colors={material:'#c7f451',energy:'#97c1ff',wear:'#f3c27c',maintenance:'#b4a1e3',labor:'#75d5b4',consumables:'#d3dace',extra:'#f29c9c'};
function Field(props){const {values,setValue,invalid,invalidDimensions}=useCalculator();const slider=props['data-slider'];const key=slider||props.name;const value=values[key];const numeric=Number(value);const rangeMax=slider?Math.max(Number(props.max),Number.isFinite(numeric)?numeric:0):props.max;const fieldInvalid=dimensions.includes(key)?invalidDimensions.includes(key):invalid.includes(key);return <input {...props} value={value} max={rangeMax} step={slider?'any':props.step} aria-invalid={slider?undefined:fieldInvalid} onChange={e=>setValue(key,e.target.value,e.target.validity.badInput)} style={slider?{'--fill':`${Math.max(0,Math.min(100,(numeric-Number(props.min))/(rangeMax-Number(props.min))*100))}%`}:undefined}/>;}
function RangeMaximum({name,base,unit}){const {values}=useCalculator();return <span>{num(Math.max(base,Number(values[name])||0))} {unit}</span>;}
function MaterialSelect(){const {materialId,chooseMaterial}=useCalculator();return <select id="materialPreset" aria-describedby="material-note" value={materialId} onChange={e=>chooseMaterial(e.target.value)}>{['PLA','PETG','Свой материал'].map(group=><optgroup key={group} label={group}>{materials.filter(m=>m.group===group).map(m=><option key={m.id} value={m.id}>{m.name}{m.price===null?'':` · ${m.price} BYN/кг`}</option>)}</optgroup>)}</select>;}
function MaterialNote(){const {material,values}=useCalculator();return <small id="material-note">{material.note}{material.price!==null&&Number(values.filamentPrice)!==material.price?' Используется ваша цена за кг.':''}</small>;}
function MaterialLink(){const {material}=useCalculator();return material.url?<a id="material-source" className="material-source" href={material.url} target="_blank" rel="noopener noreferrer">Источник цены ↗</a>:null;}
function MaterialSources(){return <div id="material-sources">{materials.filter(m=>m.url).map(m=><p key={m.id}><a href={m.url} target="_blank" rel="noopener noreferrer">{m.name} ↗</a>{m.note}</p>)}</div>;}
function TariffSelect(){const {tariffPreset,setTariff}=useCalculator();return <select id="tariffPreset" value={tariffPreset} onChange={e=>setTariff(e.target.value)}><option value="0.2581">Электроплита без газа · 0,2581 BYN/кВт·ч</option><option value="0.3037">Прочие бытовые · 0,3037 BYN/кВт·ч</option><option value="0.3265">Полное возмещение · 0,3265 BYN/кВт·ч</option><option value="custom">Свой тариф</option></select>;}
function RiskButton({value,children}){const {values,setValue}=useCalculator();const active=Number(values.failure)===value;return <button type="button" data-risk={value} className={active?'active':''} aria-pressed={active} onClick={()=>setValue('failure',String(value))}>{children}</button>;}
function FitNote(){const {invalidDimensions,parsed}=useCalculator();const complete=dimensions.every(k=>parsed[k]!==null)&&!invalidDimensions.length;const fits=complete?dimensions.every(k=>parsed[k]<=256):null;return <p id="fit-note" className={`section-note ${invalidDimensions.length||fits===false?'warning':''}`}>{invalidDimensions.length?'Исправьте заданные габариты для проверки размера. Стоимость продолжает рассчитываться.':fits===null?'Габариты необязательны. Заполните X, Y и Z для проверки поля A1: 256 × 256 × 256 мм. На стоимость они не влияют.':fits?'Габариты в пределах 256 × 256 × 256 мм. Проверьте размещение и место для каймы в слайсере.':'Размер превышает поле A1 (256 × 256 × 256 мм). Проверьте ориентацию, разделение модели или другой принтер.'}</p>;}
function Result(){const {result:r,parsed:v,invalid}=useCalculator();const parts=r?Object.entries(r.parts).filter(([key,value])=>value!==0||!['labor','extra'].includes(key)):[];return <aside className="result-column"><section className="result-card"><div className="result-top"><span className="eyebrow">СЕБЕСТОИМОСТЬ</span><span className="result-marker">BYN</span></div><p className="result-caption" id="total-caption">{r?(v.quantity===1?'За 1 успешную деталь':`За ${num(v.quantity,0)} успешных деталей`):'Себестоимость задания'}</p><div className="total" id="total" aria-live="polite" aria-atomic="true">{r?<>{money.format(r.total)}<span className="currency">BYN</span></>:'—'}</div><p className="per-unit" id="per-unit">{r?(v.quantity===1?'С учётом ожидаемых повторных попыток':`${money.format(r.perPart)} BYN / деталь · независимые печати`):'Исправьте поля для расчёта'}</p><div className="cost-bar" id="cost-bar" aria-hidden="true">{parts.map(([key,value])=><span key={key} style={{background:colors[key],width:r.perPart>0?`${value/r.perPart*100}%`:'0%'}}/>)}</div><div className="breakdown" id="breakdown">{parts.map(([key,value])=><div className="breakdown-row" key={key}><span className="key"><i className="swatch" style={{background:colors[key]}}/>{labels[key]}</span><strong>{money.format(value*v.quantity)} BYN</strong></div>)}</div><div className="risk-note"><span className="risk-icon" aria-hidden="true">↺</span><div><strong id="risk-cost">{r?`Брак: +${money.format(r.riskCost*v.quantity)} BYN уже в сумме`:'Расчёт приостановлен'}</strong><p id="risk-detail">{r?`${num(v.failure)}% неудач × ${num(v.loss)}% потерь. Переменные расходы +${num((r.factor-1)*100,2)}%. Не добавляйте резерв повторно.`:'Нет достоверного результата при неверных данных.'}</p></div></div><div className="batch-info"><div><span>Пластика с браком</span><strong id="expected-mass">{r?num(r.batchGrams)+' г':'—'}</strong></div><div><span>Времени с браком</span><strong id="expected-time">{r?num(r.batchHours,2)+' ч':'—'}</strong></div><div><span>Электроэнергии</span><strong id="expected-energy">{r?num(r.kwh*v.quantity,3)+' кВт·ч':'—'}</strong></div></div><p className="result-footnote">Себестоимость, без прибыли и налогов.<br/>Печать нескольких деталей на одном столе рассчитывайте по общим данным слайсера как одну печать.</p><div id="errors" className="error" role="alert" hidden={!invalid.length}>{invalid.length?'Проверьте выделенные поля: введите число в допустимых пределах. Ресурс должен быть от 1 часа, количество — целым от 1, вероятность брака — от 0 до 95%.':''}</div></section><div className="confidence-note"><span aria-hidden="true">i</span><p>Планируйте по своим настройкам.<br/>Точность зависит от данных слайсера, реальной мощности и вашей статистики брака.</p></div></aside>;}
export default function App(){
 const [values,setValues]=useState(initialValues);const [badInputs,setBadInputs]=useState({});const [materialId,setMaterialId]=useState(defaultMaterial);const [tariffPreset,setTariffPreset]=useState(String(defaults.tariff));
 const setValue=(key,value,bad=false)=>{setValues(prev=>({...prev,[key]:value}));setBadInputs(prev=>({...prev,[key]:bad}));if(key==='tariff')setTariffPreset('custom');};
 const chooseMaterial=id=>{setMaterialId(id);setValue('filamentPrice',materials.find(m=>m.id===id).price?.toString()??'');};
 const setTariff=preset=>{setTariffPreset(preset);if(preset!=='custom'){setValues(prev=>({...prev,tariff:preset}));setBadInputs(prev=>({...prev,tariff:false}));}};
 const reset=()=>{setValues(initialValues());setBadInputs({});setMaterialId(defaultMaterial);setTariffPreset(String(defaults.tariff));};
 const parsed=Object.fromEntries(Object.entries(values).map(([k,v])=>[k,badInputs[k]?NaN:v===''?(dimensions.includes(k)?null:NaN):Number(v)]));
 const invalid=Object.entries(bounds).filter(([k,[min,max]])=>!dimensions.includes(k)&&(!Number.isFinite(parsed[k])||parsed[k]<min||parsed[k]>max||(k==='quantity'&&!Number.isInteger(parsed[k])))).map(([k])=>k);
 const invalidDimensions=dimensions.filter(k=>parsed[k]!==null&&(!Number.isFinite(parsed[k])||parsed[k]<bounds[k][0]||parsed[k]>bounds[k][1]));
 const result=invalid.length?null:calculate(parsed);const material=materials.find(m=>m.id===materialId);
 return <Context.Provider value={{values,setValue,parsed,invalid,invalidDimensions,result,materialId,material,chooseMaterial,tariffPreset,setTariff}}>

<header className="topbar"><a className="brand" href="#" aria-label="Слой — начало"><span className="brand-symbol" aria-hidden="true">≋</span>слой<span className="brand-dot">.</span></a><span className="topnote">ДОМАШНЯЯ 3D-ПЕЧАТЬ</span><a className="country" href="#sources"><span aria-hidden="true">BY</span> Беларусь · BYN</a></header>
<main>
<div className="intro"><div><div className="eyebrow">ОДИН ПРИНТЕР. ВСЕ РАСХОДЫ.</div><h1>Сколько стоит <br />напечатать <span>деталь?</span></h1><p>От грамма пластика до последней минуты печати.</p></div><div className="intro-note"><span className="small-label">РАСЧЁТ ДЛЯ</span><strong>FDM / FFF</strong><span>пластик · домашняя мастерская</span></div></div>
<div className="workspace">
<form id="calculator" noValidate className="controls" onSubmit={e=>e.preventDefault()}>
<section className="card primary"><div className="section-heading"><span className="step">01</span><h2>Ваша деталь</h2><span className="chip">ИЗ СЛАЙСЕРА</span></div><p className="section-note">Масса модели без поддержек. Время — для одной детали. Если слайсер считает несколько деталей на одном столе, введите общий расход и количество 1.</p>
<div className="slider-field"><div className="field-top"><label htmlFor="mass">Масса модели</label><div className="numeric"><Field id="mass" name="mass" type="number" min="0" max="100000" step="0.1" value="50" /><span>г</span></div></div><Field aria-label="Масса модели, ползунок" data-slider="mass" type="range" min="0" max="2000" step="1" value="50" /><div className="range-label"><span>0 г</span><RangeMaximum name="mass" base={2000} unit="г" /></div></div>
<div className="slider-field"><div className="field-top"><label htmlFor="hours">Время печати</label><div className="numeric"><Field id="hours" name="hours" type="number" min="0" max="10000" step="0.1" value="3" /><span>ч</span></div></div><Field aria-label="Время печати, ползунок" data-slider="hours" type="range" min="0" max="48" step="0.1" value="3" /><div className="range-label"><span>0 ч</span><RangeMaximum name="hours" base={48} unit="ч" /></div></div>
<div className="two-col"><div className="field"><label htmlFor="waste">Поддержки и отходы <span className="unit">г</span></label><Field id="waste" name="waste" type="number" min="0" max="100000" step="0.1" value="8" /><small>Поддержки, кайма и продувка. Брак отдельно.</small></div><div className="field"><label htmlFor="quantity">Количество <span className="unit">шт.</span></label><Field id="quantity" name="quantity" type="number" min="1" max="10000" step="1" value="1" /><small>Одинаковые детали, отдельные печати.</small></div></div>
<details className="dimensions"><summary>Габариты детали <span>проверить размер</span></summary><div className="three-col"><div className="field"><label htmlFor="x">X · мм</label><Field id="x" name="x" type="number" min="0" max="10000" placeholder="Необязательно" /></div><div className="field"><label htmlFor="y">Y · мм</label><Field id="y" name="y" type="number" min="0" max="10000" placeholder="Необязательно" /></div><div className="field"><label htmlFor="z">Z · мм</label><Field id="z" name="z" type="number" min="0" max="10000" placeholder="Необязательно" /></div></div><FitNote /><small>Габариты не меняют стоимость. Масса и время зависят от геометрии, заполнения и настроек слайсера.</small></details>
</section>
<section className="card"><div className="section-heading"><span className="step">02</span><h2>Материал и энергия</h2></div>
<div className="field"><label htmlFor="materialPreset">Материал · бренд и катушка</label><MaterialSelect /><MaterialNote /><MaterialLink /></div>
<div className="two-col"><div className="field"><label htmlFor="filamentPrice">Цена пластика <span className="unit">BYN / кг</span></label><Field id="filamentPrice" name="filamentPrice" type="number" min="0" max="100000" step="0.1" value="44" /></div><div className="field"><label htmlFor="power">Средняя мощность <span className="unit">Вт</span></label><Field id="power" name="power" type="number" min="0" max="100000" value="100" /></div></div><p className="section-note">100 Вт — сценарное допущение для A1, а не спецификация или измерение. Измерьте среднюю мощность своей печати ваттметром.</p>
<div className="field"><label htmlFor="tariffPreset">Домашний тариф</label><TariffSelect /></div><div className="field tariff-field"><label htmlFor="tariff">Цена электричества <span className="unit">BYN / кВт·ч</span></label><Field id="tariff" name="tariff" type="number" min="0" max="100" step="0.0001" value="0.2581" /></div><small>Категорию проверьте по своей квитанции. Льготный тариф на отопление не применяется автоматически к принтеру.</small>
</section>
<section className="card"><div className="section-heading"><span className="step">03</span><h2>Принтер и брак</h2><span className="chip">A1</span></div>
<p className="section-note">Bambu Lab A1 · акционная цена 1 130 BYN <s>1 689 BYN</s> · <a href="https://mwi.by/shop/3d-printeri/a-series/bambu-lab-a1/" target="_blank" rel="noopener noreferrer">MWI.BY ↗</a></p><div className="two-col"><div className="field"><label htmlFor="printerPrice">Стоимость принтера <span className="unit">BYN</span></label><Field id="printerPrice" name="printerPrice" type="number" min="0" max="1000000" value="1130" /></div><div className="field"><label htmlFor="life">Ресурс до замены <span className="unit">ч</span></label><Field id="life" name="life" type="number" min="1" max="1000000" step="1" value="5000" /></div></div><div className="field"><label htmlFor="maintenance">Резерв на обслуживание <span className="unit">BYN / ч</span></label><Field id="maintenance" name="maintenance" type="number" min="0" max="10000" step="0.01" value="0.05" /><small>Ресурс 5 000 ч и резерв 0,05 BYN/ч — изменяемые допущения.</small></div>
<div className="slider-field risk-field"><div className="field-top"><label htmlFor="failure">Вероятность брака</label><div className="numeric"><Field id="failure" name="failure" type="number" min="0" max="95" step="1" value="10" /><span>%</span></div></div><Field aria-label="Вероятность брака, ползунок" data-slider="failure" type="range" min="0" max="50" step="1" value="10" /><div className="risk-presets" role="group" aria-label="Сценарии брака"><RiskButton value={5}>5% · налажено</RiskButton><RiskButton value={10}>10% · базовый</RiskButton><RiskButton value={20}>20% · эксперимент</RiskButton></div></div><p className="section-note">Это сценарии, а не универсальная норма. Замените своей статистикой неудачных попыток.</p>
<div className="slider-field"><div className="field-top"><label htmlFor="loss">Расход до сбоя</label><div className="numeric"><Field id="loss" name="loss" type="number" min="0" max="100" step="1" value="50" /><span>%</span></div></div><Field aria-label="Расход до сбоя, ползунок" data-slider="loss" type="range" min="0" max="100" step="1" value="50" /><small>Доля материала и времени, потерянная в среднем при неудачной попытке. 50% — допущение.</small></div>
</section>
<section className="card"><div className="section-heading"><span className="step">04</span><h2>Сопутствующие расходы</h2></div><div className="two-col"><div className="field"><label htmlFor="laborMinutes">Ручная работа <span className="unit">мин / деталь</span></label><Field id="laborMinutes" name="laborMinutes" type="number" min="0" max="100000" value="10" /></div><div className="field"><label htmlFor="laborRate">Стоимость вашего часа <span className="unit">BYN / ч</span></label><Field id="laborRate" name="laborRate" type="number" min="0" max="100000" step="0.1" value="0" /></div><div className="field"><label htmlFor="consumables">Расходники <span className="unit">BYN / деталь</span></label><Field id="consumables" name="consumables" type="number" min="0" max="100000" step="0.01" value="0.1" /></div><div className="field"><label htmlFor="extra">Другие расходы <span className="unit">BYN / деталь</span></label><Field id="extra" name="extra" type="number" min="0" max="100000" step="0.01" value="0" /></div></div><small>Ручная работа включает подготовку, снятие поддержек и ожидаемую работу с повторными попытками. Расходники: клей, очистка, крепёж. Сушка пластика — в других расходах.</small></section>
<button type="button" id="reset" className="reset" onClick={reset}>Сбросить к исходному примеру</button>
</form>
<Result />
</div>
<section className="method card"><div className="section-heading"><span className="step">∑</span><h2>Как считается стоимость</h2></div><div className="method-grid"><div><h3>Каждая попытка имеет цену</h3><p>Материал, электричество, износ и обслуживание складываются. Неудачные попытки добавляют расход пропорционально тому, на какой стадии случился сбой.</p></div><div><div className="formula">Множитель = 1 + p / (1 − p) × d</div><p>p — вероятность брака, d — доля расхода до сбоя. При 10% брака и 50% потерь переменные расходы растут на 5,56%. Труд и разовые расходники задаются отдельно на успешную деталь.</p></div></div><details><summary>Посмотреть формулы и допущения</summary><ul><li>Материал = (модель + отходы) / 1 000 × цена за кг × множитель.</li><li>Электричество = мощность / 1 000 × время × тариф × множитель.</li><li>Износ = стоимость принтера / ресурс в часах × время × множитель. Остаточная стоимость принята равной нулю.</li><li>Обслуживание = резерв за час × время × множитель.</li><li>Итог = материал + электричество + износ + обслуживание + ручной труд + расходники + другие расходы.</li><li>Количество умножает итог одной детали. Считаем одинаковые независимые печати и повторяем неудачные попытки до успеха.</li><li>Расход до сбоя одинаково применяется к материалу и времени. Это упрощение, которое можно настроить под свою практику.</li><li>Если слайсер показывает общий расход вместе с поддержками, вычтите их из массы модели либо поставьте отходы равными нулю.</li></ul></details></section>
<section id="sources" className="sources"><div className="sources-heading"><div className="eyebrow">ОТКУДА ЦИФРЫ</div><h2>Источники и допущения</h2></div><div className="source-date">Проверка: 2 октября 2026</div><div className="source-grid"><article><span className="source-category">ЭЛЕКТРИЧЕСТВО</span><h3>Бытовые тарифы 2026</h3><p>0,2581 / 0,3037 / 0,3265 BYN за кВт·ч. Постановление №93 от 25.02.2026; ставки опубликованы с 1 марта.</p><a href="https://www.gs.by/2026/03/10/novye-tarify-na-elektroenergiyu-s-1-marta-2026-goda/" target="_blank" rel="noopener noreferrer">Таблица GS.BY · 10.03.2026 ↗</a><a href="https://virtualbrest.ru/pda.php?pdaid=185837&amp;pdaurl=1" target="_blank" rel="noopener noreferrer">Публикация Бреста · 29.06.2026 ↗</a><small>Официальную страницу подтвердить не удалось. Сверьте актуальный тариф с квитанцией; данные не обновляются автоматически.</small></article><article><span className="source-category">ПЛАСТИК</span><h3>Материалы PLA и PETG</h3><MaterialSources /><small>Проверено 02.10.2026. Цена зависит от бренда, цвета, даты покупки и комплектации: катушка или refill. Доставка отдельно. Цены не загружаются автоматически.</small></article><article><span className="source-category">ПРИНТЕР</span><h3>Bambu Lab A1 · 1 130 BYN <s>1 689 BYN</s></h3><p>Акционная цена MWI.BY на 02.10.2026. Поле печати 256 × 256 × 256 мм.</p><a href="https://mwi.by/shop/3d-printeri/a-series/bambu-lab-a1/" target="_blank" rel="noopener noreferrer">Цена в MWI.BY ↗</a><small>100 Вт — сценарное допущение для A1; измерьте ваттметром. Ресурс, обслуживание и брак — допущения, а не характеристики производителя.</small></article></div></section>
<footer><a className="brand" href="#">слой.</a><span>Считайте расходы. Печатайте осознанно.</span><span>Беларусь / FDM</span></footer>
</main>
</Context.Provider>;
}
